version: '3.8'

services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-app-image:latest
    container_name: quiz-app-container
    ports:
      - "3000:3000"
    env_file:
      - .dockerenv
    networks:
      - custom-quiz-app-network
    restart: unless-stopped

networks:
  custom-quiz-app-network:
    name: quiz-app-network
    driver: bridge